//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeakerAutoVolume.Persistence.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpeakerAutoVolume.Persistence.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from Schedule where Name=&apos;{0}&apos;.
        /// </summary>
        internal static string DeleteSchedule {
            get {
                return ResourceManager.GetString("DeleteSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from ScheduleDetail where ScheduleID = (select ID from Schedule where Name = &apos;{0}&apos;) and StartHour = {1} and StartMinute = {2} and EndHour = {3} and EndMinute = {4} and Volume = {5}.
        /// </summary>
        internal static string DeleteScheduleDetail {
            get {
                return ResourceManager.GetString("DeleteScheduleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from ScheduleDetail where ScheduleID = (select ID from Schedule where Name = &apos;{0}&apos;).
        /// </summary>
        internal static string DeleteScheduleDetails {
            get {
                return ResourceManager.GetString("DeleteScheduleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert or ignore into Schedule (Name) values (&apos;{0}&apos;);.
        /// </summary>
        internal static string InsertSchedule {
            get {
                return ResourceManager.GetString("InsertSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into ScheduleDetail (StartHour,StartMinute,EndHour, EndMinute,Volume,ScheduleID) values ({0},{1},{2},{3},{4}, (select ID from Schedule where Schedule.Name = &apos;{5}&apos;));.
        /// </summary>
        internal static string InsertScheduleDetail {
            get {
                return ResourceManager.GetString("InsertScheduleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Name from Schedule.
        /// </summary>
        internal static string SelectAllSchedule {
            get {
                return ResourceManager.GetString("SelectAllSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Schedule.Name as ScheduleName, ScheduleDetail.StartHour, ScheduleDetail.StartMinute, ScheduleDetail.EndHour, ScheduleDetail.EndMinute, ScheduleDetail.Volume from Schedule inner join ScheduleDetail on Schedule.ID = ScheduleDetail.ScheduleID.
        /// </summary>
        internal static string SelectAllScheduleDetail {
            get {
                return ResourceManager.GetString("SelectAllScheduleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 1 from ScheduleDetail where ScheduleID = (select ID from Schedule where Name = &apos;{0}&apos;) and StartHour = {1} and StartMinute = {2} and EndHour = {3} and EndMinute = {4} and Volume = {5}.
        /// </summary>
        internal static string SelectScheduleDetailExist {
            get {
                return ResourceManager.GetString("SelectScheduleDetailExist", resourceCulture);
            }
        }
    }
}
